### ISSUE TITLE
Trajectory

### ISSUE THREAD

**Issue by AngelSantiba** [richiecarmichael/Esri-Satellite-Map#1]
Hello at ESRI Satelitte MAP I need to select the path in a week but I can not do it. Use the program in 2015 and you could select this option and now there are no buttons. Can you help me?.
I'm from Chile, excuse my English :)
Chaoo

**Comment by richiecarmichael** [comment]
Hi @AngelSantiba,
You can control what is displayed when a satellite is clicked [here](https://github.com/richiecarmichael/Esri-Satellite-Map/blob/b40d926003b80bceaa845d70f793757660e7016a/renderer.js#L361-L395).
This will currently show the orbit of the satellite.  The app will render the orbit using 1,000 computed positions along the orbit.
Hope this helps!
