### ISSUE TITLE
DELTA 1 DEB

### ISSUE THREAD

**Issue by ismShahriyar** [richiecarmichael/Esri-Satellite-Map#2]
This shlould be in LEO
NORAD | 21350
-- | --
COSPAR | 1975-052BU
Country | US
Period | 92.19 min
Inclination | 99.35°
Apogee | 390 km
Perigee | 374 km
Size | SMALL
Launch | 12/06/1975

Should be on LEO but in map, it is too far from this constellation

**Comment by richiecarmichael** [comment]
Hi @ismShahriyar,
I just updated the ephemeris. It looks like 1975-052BU is not longer in the database. Perhaps it's orbit has decayed and has subsequently burned up?
Thanks!
